---
- hosts: localhost
  vars:
    conda_home: /opt/conda
    conda_home_bin: /opt/conda/bin
    conda_installer: /opt/conda/anaconda.sh
  tasks:
  - name: create conda home
    shell: sudo mkdir -p {{ conda_home }} && sudo chown -R $USER:$USER {{ conda_home }}

  - name: install apt packages
    apt:
      name:
      - build-essential
      - git
      - bzip2
      update_cache: yes
      state: latest
    become: yes
    become_method: sudo
 
  - name: download anaconda installer
    get_url:
      url: https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh
      dest: "{{ conda_installer }}"
      mode: 0755

  - name: install anaconda
    shell: bash {{ conda_installer }} -b -u -p {{ conda_home }}

  - name: add conda path to path .bashrc
    lineinfile:
      dest: $HOME/.bashrc
      regexp: "# ansible-anaconda-path"
      line: "$PATH=$PATH:{{ conda_home_bin }}  # ansible-anaconda-path"

  - name: install jupyter extension
    shell: ./pip install jupyter_http_over_ws && ./jupyter serverextension enable --py jupyter_http_over_ws --user
    args:
      chdir: "{{ conda_home_bin }}"
      
  - name: install systemd service
    copy:
      src: jupyter-colab@.service
    dest: /etc/systemd/system/
    become: yes
    become_method: sudo

  - name: enable service
    systemd:
      name: "jupyter-colab@{{ lookup('env','USER') }}.service" 
      state: started
      enabled: True
      daemon_reload: yes
    become: yes
    become_method: sudo
